# Generated by Django 6.0.6 on 2026-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='created_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='church',
            field=models.CharField(max_length=100),
        ),
    ]
