# Generated by Django 6.0.6 on 2026-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_remove_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
