# Generated by Django 6.0.6 on 2026-07-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registration_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_number',
            field=models.CharField(blank=True, default='AC2026-0000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
