# Generated by Django 6.0.6 on 2026-07-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_registration_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.CharField(default='No address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='family_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
