# Generated by Django 6.0.6 on 2026-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_address_registration_family_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('Adult', 'Adult ($20)'), ('Youth', 'Youth ($10)'), ('Young Generation', 'Young Generation ($5)')], default='Adult', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='pledge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
