# Generated by Django 6.0.6 on 2026-07-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_registration_category_registration_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='category',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='family_size',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='registration_type',
        ),
        migrations.AddField(
            model_name='registration',
            name='adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='registration',
            name='young_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='youths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
