# Generated by Django 6.0.6 on 2026-07-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_remove_registration_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='young_generation',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='youths',
        ),
        migrations.AddField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult ($20)'), ('youth', 'Youth ($10)'), ('young_gen', 'Young Generation ($5)')], default='adult', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='family_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('family', 'Family')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(default='harare', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pledge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
