# Generated by Django 6.0.6 on 2026-07-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_remove_registration_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult ($20)'), ('youth', 'Youth ($10)'), ('young', 'Young Generation ($5)')], default='adult', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
