# Generated by Django 6.0.6 on 2026-07-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_alter_registration_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
