# Generated by Django 6.0.6 on 2026-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_remove_registration_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='pledge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
