# Generated by Django 6.0.6 on 2026-07-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0011_remove_registration_total_amount_registration_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='family_size',
        ),
        migrations.AddField(
            model_name='registration',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='young_generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='youths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
