# Generated by Django 6.0.6 on 2026-07-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_remove_registration_family_size_registration_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
