# Generated by Django 6.0.6 on 2026-07-03 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_registration_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
