# Generated by Django 6.0.6 on 2026-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_alter_registration_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='youths',
            new_name='sunday_school',
        ),
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult ($20)'), ('young', 'Young Generation ($10)'), ('sunday', 'Sunday School ($5)')], default='adult', max_length=20),
        ),
    ]
