# Generated by Django 6.0.6 on 2026-07-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0015_rename_youths_registration_sunday_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult ($20)'), ('youth', 'Young Generation ($10)'), ('young', 'Sunday School ($5)')], default='adult', max_length=20),
        ),
    ]
