# Generated by Django 6.0.6 on 2026-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_alter_registration_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult ($20)'), ('young_generation', 'Young Generation ($10)'), ('sunday_school', 'Sunday School ($5)')], default='adult', max_length=30),
        ),
    ]
